
log_wave -r /
set designtopgroup [add_wave_group "Design Top Signals"]
set cinputgroup [add_wave_group "C Inputs" -into $designtopgroup]
set clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group [add_wave_group clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions(axi_slave) -into $cinputgroup]
add_wave /apatb_fpu_top_top/AESL_inst_fpu_top/s_axi_control_BRESP -into $clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -radix hex
add_wave /apatb_fpu_top_top/AESL_inst_fpu_top/s_axi_control_BREADY -into $clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/AESL_inst_fpu_top/s_axi_control_BVALID -into $clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/AESL_inst_fpu_top/s_axi_control_RRESP -into $clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -radix hex
add_wave /apatb_fpu_top_top/AESL_inst_fpu_top/s_axi_control_RDATA -into $clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -radix hex
add_wave /apatb_fpu_top_top/AESL_inst_fpu_top/s_axi_control_RREADY -into $clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/AESL_inst_fpu_top/s_axi_control_RVALID -into $clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/AESL_inst_fpu_top/s_axi_control_ARREADY -into $clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/AESL_inst_fpu_top/s_axi_control_ARVALID -into $clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/AESL_inst_fpu_top/s_axi_control_ARADDR -into $clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -radix hex
add_wave /apatb_fpu_top_top/AESL_inst_fpu_top/s_axi_control_WSTRB -into $clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -radix hex
add_wave /apatb_fpu_top_top/AESL_inst_fpu_top/s_axi_control_WDATA -into $clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -radix hex
add_wave /apatb_fpu_top_top/AESL_inst_fpu_top/s_axi_control_WREADY -into $clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/AESL_inst_fpu_top/s_axi_control_WVALID -into $clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/AESL_inst_fpu_top/s_axi_control_AWREADY -into $clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/AESL_inst_fpu_top/s_axi_control_AWVALID -into $clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/AESL_inst_fpu_top/s_axi_control_AWADDR -into $clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -radix hex
set resetgroup [add_wave_group "Reset" -into $designtopgroup]
add_wave /apatb_fpu_top_top/AESL_inst_fpu_top/ap_rst_n -into $resetgroup
set clockgroup [add_wave_group "Clock" -into $designtopgroup]
add_wave /apatb_fpu_top_top/AESL_inst_fpu_top/ap_clk -into $clockgroup
set testbenchgroup [add_wave_group "Test Bench Signals"]
set tbinternalsiggroup [add_wave_group "Internal Signals" -into $testbenchgroup]
set tb_simstatus_group [add_wave_group "Simulation Status" -into $tbinternalsiggroup]
set tb_portdepth_group [add_wave_group "Port Depth" -into $tbinternalsiggroup]
add_wave /apatb_fpu_top_top/AUTOTB_TRANSACTION_NUM -into $tb_simstatus_group -radix hex
add_wave /apatb_fpu_top_top/ready_cnt -into $tb_simstatus_group -radix hex
add_wave /apatb_fpu_top_top/done_cnt -into $tb_simstatus_group -radix hex
add_wave /apatb_fpu_top_top/LENGTH_ce_r -into $tb_portdepth_group -radix hex
add_wave /apatb_fpu_top_top/LENGTH_clk -into $tb_portdepth_group -radix hex
add_wave /apatb_fpu_top_top/LENGTH_exceptions -into $tb_portdepth_group -radix hex
add_wave /apatb_fpu_top_top/LENGTH_op -into $tb_portdepth_group -radix hex
add_wave /apatb_fpu_top_top/LENGTH_operand_a -into $tb_portdepth_group -radix hex
add_wave /apatb_fpu_top_top/LENGTH_operand_b -into $tb_portdepth_group -radix hex
add_wave /apatb_fpu_top_top/LENGTH_precision -into $tb_portdepth_group -radix hex
add_wave /apatb_fpu_top_top/LENGTH_precision_out -into $tb_portdepth_group -radix hex
add_wave /apatb_fpu_top_top/LENGTH_result -into $tb_portdepth_group -radix hex
add_wave /apatb_fpu_top_top/LENGTH_rst_n -into $tb_portdepth_group -radix hex
add_wave /apatb_fpu_top_top/LENGTH_valid_in -into $tb_portdepth_group -radix hex
add_wave /apatb_fpu_top_top/LENGTH_valid_out -into $tb_portdepth_group -radix hex
set tbcinputgroup [add_wave_group "C Inputs" -into $testbenchgroup]
set tb_clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group [add_wave_group clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions(axi_slave) -into $tbcinputgroup]
add_wave /apatb_fpu_top_top/control_BRESP -into $tb_clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -radix hex
add_wave /apatb_fpu_top_top/control_BREADY -into $tb_clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/control_BVALID -into $tb_clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/control_RRESP -into $tb_clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -radix hex
add_wave /apatb_fpu_top_top/control_RDATA -into $tb_clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -radix hex
add_wave /apatb_fpu_top_top/control_RREADY -into $tb_clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/control_RVALID -into $tb_clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/control_ARREADY -into $tb_clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/control_ARVALID -into $tb_clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/control_ARADDR -into $tb_clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -radix hex
add_wave /apatb_fpu_top_top/control_WSTRB -into $tb_clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -radix hex
add_wave /apatb_fpu_top_top/control_WDATA -into $tb_clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -radix hex
add_wave /apatb_fpu_top_top/control_WREADY -into $tb_clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/control_WVALID -into $tb_clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/control_AWREADY -into $tb_clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/control_AWVALID -into $tb_clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -color #ffff00 -radix hex
add_wave /apatb_fpu_top_top/control_AWADDR -into $tb_clk__rst_n__ce_r__valid_in__precision__op__operand_a__operand_b__valid_out__precision_out__result__exceptions_group -radix hex
save_wave_config fpu_top.wcfg
run all
quit

